// c.SsrFramework/NuxtProject/app.vue
<template>
  <div>
    <button @click="login">Login</button>
    <button @click="test">Test</button>
  </div>
</template>

<script setup> 
const login = () => fetch('http://localhost:5113/api/login', {method: 'post', credentials: 'include'})
const test = () => fetch('http://localhost:5113/api/test', {credentials: 'include'})
</script>

// a.Together/reactproject1/src/App.jsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const login = () => fetch('/api/login', {method: 'post'})
  const test = () => fetch('/api/test')
  return (
    <div className='App'>
    <button onClick={login}> Login</button>
    <button onClick={test}> Test</button>
    </div>
  )
}

export default App
