// b.Separate/solid-project/src/app.jsx
import { MetaProvider, Title } from "@solidjs/meta";
import { Router } from "@solidjs/router";
import { FileRoutes } from "@solidjs/start/router";
import { Suspense } from "solid-js";
import "./app.css";

 function App() {
  const login = () => fetch('/api/login', {method: 'post'})
  return (
   <div class={styles.App}>
   <button onClick={login}>Login</button>
   </div>
  );
}

// a.Together/reactproject1/src/App.jsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const login = () => fetch('/api/login', {method: 'post'})
  const test = () => fetch('/api/test')
  return (
    <div className='App'>
    <button onClick={login}> Login</button>
    <button onClick={test}> Test</button>
    </div>
  )
}

export default App
